jobs:
  tests:
    name: Tests
    run_when:
      any branch has been updated:
        type: branch
        include_match: ^.*$
    context:
      generate_tasks:
        include_match: test/.*_test.clj
      task_defaults:
        traits:
          'Leiningen 2': true
        scripts:
          test:
            body:
              lein test $CIDER_CI_TASK_FILE
